CREATE TABLE customer
(
    id_customer   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    last_name     VARCHAR(255),
    run           VARCHAR(255),
    city          VARCHAR(255),
    commune       VARCHAR(255),
    street        VARCHAR(255),
    number        INT                                     NOT NULL,
    date_of_birth date,
    phone         VARCHAR(255),
    is_active     BOOLEAN,
    CONSTRAINT pk_customer PRIMARY KEY (id_customer)
);

CREATE TABLE plans
(
    id_plans          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    price             INT                                     NOT NULL,
    services_provided VARCHAR(255),
    active            BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_plans PRIMARY KEY (id_plans)
);

CREATE TABLE contracts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT,
    plan_id     BIGINT,
    start_date  date,
    end_date    date,
    CONSTRAINT pk_contracts PRIMARY KEY (id)
);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id_customer);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_PLAN FOREIGN KEY (plan_id) REFERENCES plans (id_plans);

